language: node_js

node_js:
  - "8"
  - "10"

sudo: false

branches:
  only:
    - master

# (Optional) Cache yarn installs for faster builds.
cache: yarn

install:
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

script:
  - yarn run lint
  - yarn run test
  - yarn run build
